export const services = [
  {
    id: 1,
    name: "Facial Treatment",
    description: "Whitening, Vitamin C, Oxygen, Hydrating & Collagen",
    duration: "60-90 min",
    price: "RM 220.00",
  },
  {
    id: 2,
    name: "Deep Cleansing",
    description: "Deep cleansing facial treatment",
    duration: "45-60 min",
    price: "RM 99.00",
  },
  {
    id: 3,
    name: "Student Deep Cleansing Facial",
    description: "Deep cleansing facial for students",
    duration: "45-60 min",
    price: "RM 88.00",
  },
  {
    id: 4,
    name: "Acne Pacne",
    description: "Specialized treatment for acne-prone skin",
    duration: "60 min",
    price: "RM 218.00",
  },
  {
    id: 5,
    name: "Men Facial",
    description: "Facial treatment specially formulated for men",
    duration: "60 min",
    price: "RM 218.00",
  },
  {
    id: 6,
    name: "Vitamin C Treatment",
    description: "Brightening and antioxidant treatment",
    duration: "60 min",
    price: "RM 250.00",
  },
  {
    id: 7,
    name: "Hydrating Treatment",
    description: "Deep hydration for dry and dehydrated skin",
    duration: "60 min",
    price: "RM 180.00",
  },
  {
    id: 8,
    name: "Collagen Treatment",
    description: "Anti-aging treatment to boost collagen production",
    duration: "60 min",
    price: "RM 250.00",
  },
  {
    id: 9,
    name: "Brightening Treatment",
    description: "Treatment for even skin tone and radiance",
    duration: "60-90 min",
    price: "RM 280.00",
  },
  {
    id: 10,
    name: "Eye Treatment",
    description: "Targeted treatment for the delicate eye area",
    duration: "30-45 min",
    price: "RM 138++",
  },
  {
    id: 11,
    name: "Luxurious Gold Therapy",
    description: "Premium gold-infused facial treatment",
    duration: "90 min",
    price: "RM 350.00",
  },
  {
    id: 12,
    name: "Indulge Wellness Therapy",
    description: "Holistic wellness facial treatment",
    duration: "90 min",
    price: "RM 350.00",
  },
  {
    id: 13,
    name: "Double Oxy Jet Elixir Treatment",
    description: "Advanced oxygen infusion treatment",
    duration: "90 min",
    price: "RM 380.00",
  },
  {
    id: 14,
    name: "Luxury Gold Therapy",
    description: "Premium gold therapy for skin rejuvenation",
    duration: "90 min",
    price: "RM 499.00",
  },
  {
    id: 15,
    name: "Bio V-Lift Needle Free Treatment",
    description: "Non-invasive lifting and firming treatment",
    duration: "90 min",
    price: "RM 599.00",
  },
  {
    id: 16,
    name: "Eyebrow Embroidery",
    description: "Semi-permanent eyebrow enhancement",
    duration: "120 min",
    price: "RM 800.00",
  },
  {
    id: 17,
    name: "Eyebrow Microblading",
    description: "Precise hair-stroke technique for natural-looking brows",
    duration: "120-150 min",
    price: "RM 1200++",
  },
  {
    id: 18,
    name: "Eye Liner",
    description: "Semi-permanent eyeliner application",
    duration: "90 min",
    price: "RM 600.00",
  },
  {
    id: 19,
    name: "Lip Embroidery",
    description: "Semi-permanent lip color enhancement",
    duration: "120 min",
    price: "RM 1500.00",
  },
  {
    id: 20,
    name: "Waxing",
    description: "Hair removal service",
    duration: "30 min",
    price: "RM 30++",
  },
  {
    id: 21,
    name: "Waxing - Hand/Leg/Armpit",
    description: "Targeted hair removal for specific areas",
    duration: "15-30 min",
    price: "RM 15++",
  },
  {
    id: 22,
    name: "Mole Remover",
    description: "Safe removal of unwanted moles",
    duration: "30 min",
    price: "RM 180++",
  },
  {
    id: 23,
    name: "Bridal/Function Makeup",
    description: "Professional makeup for special occasions",
    duration: "60-90 min",
    price: "RM 10++",
  },
  {
    id: 24,
    name: "Trim Eyebrows",
    description: "Eyebrow shaping and maintenance",
    duration: "15 min",
    price: "RM 10++",
  },
];
