export const products = [
  {
    id: 1,
    name: "Hydrating Shampoo",
    description: "Nourishing shampoo for all hair types",
    price: 29.99,
    image: "/products/shampoo.jpg",
    category: "Hair Care",
  },
  {
    id: 2,
    name: "Anti-Aging Serum",
    description: "Advanced formula to reduce fine lines",
    price: 49.99,
    image: "/products/serum.jpg",
    category: "Skincare",
  },
  {
    id: 3,
    name: "Body Lotion",
    description: "Rich moisturizing body lotion",
    price: 24.99,
    image: "/products/lotion.jpg",
    category: "Body Care",
  },
  {
    id: 4,
    name: "Hair Mask",
    description: "Deep conditioning treatment",
    price: 34.99,
    image: "/products/hair-mask.jpg",
    category: "Hair Care",
  },
  {
    id: 5,
    name: "Facial Cleanser",
    description: "Gentle daily cleanser",
    price: 22.99,
    image: "/products/cleanser.jpg",
    category: "Skincare",
  },
  {
    id: 6,
    name: "Hand Cream",
    description: "Intensive hand repair cream",
    price: 19.99,
    image: "/products/hand-cream.jpg",
    category: "Body Care",
  },
];
